name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make zlib1g-dev

    - name: Build modular architecture
      run: make all

    - name: Run tests
      run: make test

    - name: Show build info
      run: make info